[@ww.select cssClass="builderSelectWidget" labelKey='executable.type' name='label'
            list=uiConfigBean.getExecutableLabels('puppet-lint') /]

[@ww.checkbox labelKey='puppet.lint.fail-on-warnings'
                  name='failOnWarnings'
                  toggle='true' /]              
[@ww.checkbox labelKey='puppet.lint.no-right_to_left_relationship-check'
                  name='noRtlRelationshipCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-autoloader_layout-check'
                  name='noAutoloaderLayoutCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-names_containing_dash-check'
                  name='noNamesContainingDashCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-class_inherits_from_params_class-check'
                  name='noClassInheritsFromParamsClassCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-class_parameter_defaults-check'
                  name='noClassParameterDefaultsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-parameter_order-check'
                  name='noParameterOrderCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-inherits_across_namespaces-check'
                  name='noInheritsAcrossNamespacesCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-nested_classes_or_defines-check'
                  name='noNestedClassesOrDefinesCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-variable_scope-check'
                  name='noVariableScopeCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-slash_comments-check'
                  name='noSlashCommentsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-star_comments-check'
                  name='noStarCommentsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-selector_inside_resource-check'
                  name='noSelectorInsideResourceCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-case_without_default-check'
                  name='noCaseWithoutDefaultCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-documentation-check'
                  name='noDocumentationCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-double_quoted_strings-check'
                  name='noDoubleQuotedStringsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-only_variable_string-check'
                  name='noOnlyVariableStringCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-variables_not_enclosed-check'
                  name='noVariablesNotEnclosedCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-single_quote_string_with_variables-check'
                  name='lint.noSingleQuoteStringWithVariablesCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-quoted_booleans-check'
                  name='noQuotedBooleansCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-variable_contains_dash-check'
                  name='noVariableContainsDashCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-hard_tabs-check'
                  name='noHardTabsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-trailing_whitespace-check'
                  name='noTrailingWhitespaceCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-80chars-check'
                  name='no80charsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-2sp_soft_tabs-check'
                  name='no2spSoftTabsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-arrow_alignment-check'
                  name='noArrowAlignmentCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-unquoted_resource_title-check'
                  name='noUnquotedResourceTitleCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-ensure_first_param-check'
                  name='noEnsureFirstParamCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-duplicate_params-check'
                  name='noDuplicateParamsCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-unquoted_file_mode-check'
                  name='noUnquotedFileModeCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-file_mode-check'
                  name='noFileModeCheck'
                  toggle='false' /]
[@ww.checkbox labelKey='puppet.lint.no-ensure_not_symlink_target-check'
                  name='noEnsureNotSymlinkTargetCheck'
                  toggle='false' /]                
